language: php
sudo: false

matrix:
  include:
    - php: 5.3
      env: CODECEPTION_URL="http://codeception.com/releases/1.8.7/codecept.phar"
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0

env:
  CODECEPTION_URL="http://codeception.com/codecept.phar"

before_script:
  - wget ${CODECEPTION_URL}

script:
  - php codecept.phar run
